In [3]:
import pandas as pd

sheet_id = '1a06tAjq1ZRYI2rkMj5Tl2YKN2KpXkZxiI9we72LfmJU'
sheet_gid = "0"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={sheet_gid}"
foods_df = pd.read_csv(url, index_col="student").drop(columns=['age', 'favorite_color'])
foods_df

,broccoli,brussels_sprouts,hamburger,oysters (raw),onion (raw),peas,olives,blue_cheese,whisky
student,,,,,,,,,
Benno,3.0,4.0,8.0,4,6.0,4,3.0,3,5.0
Derek,7.0,5.0,0.0,0,5.0,7,9.0,9,9.0
Farnoosh,8.0,7.0,4.0,2,2.0,5,9.0,9,8.0
Kwabena,8.5,5.5,7.5,5,6.5,8,8.5,5,9.5
Oleksandra,8.0,8.0,5.0,0,8.0,5,10.0,5,5.0
Sanaz,7.0,5.0,4.0,0,1.0,9,10.0,5,3.0
Mersiha,8.0,8.0,9.0,0,0.0,10,10.0,5,0.0

####Exercise 1: Import the K-Means model and initialize it with a random state and number of clusters

In [4]:
from sklearn.cluster import KMeans

k = 3  # number of clusters
kmeans = KMeans(n_clusters=k, random_state=42)

#####Hint:

Take a look at the documentation [here](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html)<br>
At the very top it says `class sklearn.cluster.KMeans(`... This is kind of like a file path telling us where to find the model in the library. So to import it we run `from sklearn.cluster import KMeans`.<br><br>
To initialize the model we call it like a function with parameters and assign the result to a variable: `model = KMeans(param = _____, param = _____)` You can look at the documentation to find what the names are for the parameters that we have to use to initialize it with a random state and number of clusters.

####Exercise 2: Fit the model to the food data imported above

In [6]:
kmeans.fit(foods_df)

print(kmeans.cluster_centers_)

[[ 7.875  6.375  4.125  1.75   5.375  6.25   9.125  7.     7.875]
 [ 7.5    6.5    6.5    0.     0.5    9.5   10.     5.     1.5  ]
 [ 3.     4.     8.     4.     6.     4.     3.     3.     5.   ]]

#####Hint:

Fit the model to the data using the `.fit()` method

####Exercise 3: Extract the cluster assignments from the model and add them as a new column to `foods_df`

In [7]:
foods_df["cluster"] = kmeans.labels_

foods_df

,broccoli,brussels_sprouts,hamburger,oysters (raw),onion (raw),peas,olives,blue_cheese,whisky,cluster
student,,,,,,,,,,
Benno,3.0,4.0,8.0,4,6.0,4,3.0,3,5.0,2
Derek,7.0,5.0,0.0,0,5.0,7,9.0,9,9.0,0
Farnoosh,8.0,7.0,4.0,2,2.0,5,9.0,9,8.0,0
Kwabena,8.5,5.5,7.5,5,6.5,8,8.5,5,9.5,0
Oleksandra,8.0,8.0,5.0,0,8.0,5,10.0,5,5.0,0
Sanaz,7.0,5.0,4.0,0,1.0,9,10.0,5,3.0,1
Mersiha,8.0,8.0,9.0,0,0.0,10,10.0,5,0.0,1

In [8]:
foods_df.groupby("cluster").mean()

,broccoli,brussels_sprouts,hamburger,oysters (raw),onion (raw),peas,olives,blue_cheese,whisky
cluster,,,,,,,,,
0,7.875,6.375,4.125,1.75,5.375,6.25,9.125,7.0,7.875
1,7.500,6.500,6.500,0.00,0.500,9.50,10.000,5.0,1.500
2,3.000,4.000,8.000,4.00,6.000,4.00,3.000,3.0,5.000

#####Hint:

Extract a list of cluster assignments from the model using `model.labels_`

####Exercise 4: Sort the data frame by the cluster assignments to more easily see the groupings

In [9]:
foods_df = foods_df.sort_values("cluster")
foods_df

,broccoli,brussels_sprouts,hamburger,oysters (raw),onion (raw),peas,olives,blue_cheese,whisky,cluster
student,,,,,,,,,,
Derek,7.0,5.0,0.0,0,5.0,7,9.0,9,9.0,0
Farnoosh,8.0,7.0,4.0,2,2.0,5,9.0,9,8.0,0
Kwabena,8.5,5.5,7.5,5,6.5,8,8.5,5,9.5,0
Oleksandra,8.0,8.0,5.0,0,8.0,5,10.0,5,5.0,0
Mersiha,8.0,8.0,9.0,0,0.0,10,10.0,5,0.0,1
Sanaz,7.0,5.0,4.0,0,1.0,9,10.0,5,3.0,1
Benno,3.0,4.0,8.0,4,6.0,4,3.0,3,5.0,2

#####Hint:

`df.sort_values()`



```
# This is formatted as code
```

####BONUS: Try it again with a different number of clusters

In [12]:
from sklearn.cluster import KMeans

for k in range(2,6):
    kmeans = KMeans(n_clusters=k, random_state=42
    )
    kmeans.fit(foods_df.drop(columns="cluster"))
    foods_df[f"cluster_{k}"] = kmeans.labels_

foods_df

,broccoli,brussels_sprouts,hamburger,oysters (raw),onion (raw),peas,olives,blue_cheese,whisky,cluster,cluster_2,cluster_3,cluster_4,cluster_5
student,,,,,,,,,,,,,,
Derek,7.0,5.0,0.0,0,5.0,7,9.0,9,9.0,0,1,2,2,2
Farnoosh,8.0,7.0,4.0,2,2.0,5,9.0,9,8.0,0,1,2,2,2
Kwabena,8.5,5.5,7.5,5,6.5,8,8.5,5,9.5,0,0,0,0,0
Oleksandra,8.0,8.0,5.0,0,8.0,5,10.0,5,5.0,0,0,0,0,0
Mersiha,8.0,8.0,9.0,0,0.0,10,10.0,5,0.0,1,1,1,1,4
Sanaz,7.0,5.0,4.0,0,1.0,9,10.0,5,3.0,1,1,1,1,1
Benno,3.0,4.0,8.0,4,6.0,4,3.0,3,5.0,2,0,0,3,3

#####Hint:

Simply adjust the `n_clusters` parameter when initializing and rerun the code you wrote before